schema_version: v0.0.1

environment:
  import: ./env.yml

application:
  import: ./workerApp.yml

deployment:
  name: WorkerDeployment
  description: Worker Deployment
  deploymentConfig:
    artifact:
      id: 3e9f0abf-c768-499d-8c46-52455622dc
    template:
      moduleRefId: aws:basic-eks-regional@1
      inputs:
        cluster: "$cluster"
        region:  "$region"
        roleArn:  "$roleArn"
    env:
      cluster: "${terraform.cluster_name.value}"
      region: "${terraform.cluster_region.value}"
      roleArn: "${terraform.eks_arn.value}"
      PG_HOST: "${terraform.rds_instance_address.value}"
      REDIS_HOST: "${terraform.redis_hostname.value}"