schema_version: v0.0.1

environment:
  import: ./env.yml

application:
  import: ./journalApp.yml

deployment:
  name: JournalDeployment
  description: Journal Service Deployment
  deploymentConfig:
    artifact:
      id: 3e9f0abf-c768-499d-8c46-577777222dc
    template:
      moduleRefId: aws:basic-eks-regional@1
      inputs:
        cluster: "$cluster"
        region:  "$region"
        roleArn:  "$roleArn"
        ports:
          -  name: "journal"
             containerPort: 80
             protocol: "TCP"
             healthCheck: "/health"
    env:
      cluster: "${terraform.cluster_name.value}"
      region: "${terraform.cluster_region.value}"
      roleArn: "${terraform.eks_arn.value}"
      PG_HOST: "${terraform.rds_instance_address.value}"
    summary:
      - name: Service URL
        command: sleep 10 ; echo http://`kubectl get ingress -n journal-app -o=jsonpath={.items[*].status.loadBalancer.ingress[*].hostname}`
